# Generated by Django 4.0.6 on 2022-09-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='user',
        ),
        migrations.AddField(
            model_name='rooms',
            name='img',
            field=models.ImageField(default=1, upload_to='pic'),
            preserve_default=False,
        ),
    ]
